import Head from "next/head";
import { Layout } from "../components/Layout/Layout";
import { Hero } from "../components/Hero/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Houm Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://houm.com/static/brandImage/houmLogo.svg"
        />
      </Head>

      <Layout>
        <Hero />
      </Layout>
      <style jsx>{``}</style>
    </>
  );
}

// Home.getInitialProps = () => {};
