import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Layout } from '../components/Layout/Layout';

export default function Home() {
	return (
		<>
			<Head>
				<title>Houm Challenge</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='https://houm.com/static/brandImage/houmLogo.svg' />
			</Head>

			<Layout className={styles.main}>HOME</Layout>
			<style jsx>{``}</style>
		</>
	);
}

// Home.getInitialProps = () => {};
